name: Generate snake animation

on:
  schedule: # Schedule the job to run every 12 hours
    - cron: "0 */12 * * *" # Adjusted to trigger at the start of every 12th hour

  workflow_dispatch: # Allow manual triggering of the workflow

  push:
    branches:
    - master # Trigger the workflow on pushes to the master branch

jobs:
  generate:
    permissions:
      contents: write # Allow the job to write to the repository
    runs-on: ubuntu-latest # Use the latest Ubuntu runner
    timeout-minutes: 5 # Set a timeout of 5 minutes for the job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Checkout the repository to the runner

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }} # Set the GitHub username
          outputs: dist/snake.svg?palette=github-dark # Generate the snake.svg with the specified palette

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output # Set the target branch for the output
          build_dir: dist # Specify the directory containing the generated snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use the GitHub token stored in secrets
